load(
    "@pip_example//:requirements.bzl",
    "data_requirement",
    "dist_info_requirement",
    "entry_point",
    "requirement",
)

py_binary(
    name = "basic_triaxial_ellipsoid_example",
    srcs = ["basic_triaxial_ellipsoid_example.py"],
    python_version = "PY3",
    deps = [
        requirement("numpy"),
        requirement("matplotlib"),
        requirement("PyQt6"),
        requirement("PySide6"),
        #        requirement("
        #        requirement("
        "@//pydin:pydin",
    ],
)
